version: "3.8"

services:
  # Backend service
  backend:
    build: ./car-insurance-recommendation-backend-docker
    ports:
      - "3000:3000"
    environment:
      GOOGLE_API_KEY: "YOUR_ACTUAL_GOOGLE_API_KEY"
      MONGO_URI: "mongodb://myappuser:takashi123@mongodb:27017/insuranceDB?authSource=insuranceDB"
    restart: always
    container_name: insurance-backend
    depends_on:
      - mongodb

  # Frontend service
  frontend:
    build: ./car-insurance-recommendation-frontend-docker
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    container_name: insurance-frontend

  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: myappuser
      MONGO_INITDB_ROOT_PASSWORD: takashi123
    restart: always
    container_name: insurance-mongodb

# Named volume for MongoDB persistent data
volumes:
  mongodb_data:


